name: Morning Brief (Phase 1)

on:
  schedule:
    # 06:00 Asia/Jakarta (UTC+7) Monday–Friday == 23:00 UTC Sunday–Thursday
    - cron: "0 23 * * 0-4"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: morning-brief
  cancel-in-progress: true

jobs:
  run-brief:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Morning Brief (Phase 1)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m daily_brief.orchestrator

      - name: Upload outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: morning-brief-${{ github.run_id }}
          path: outputs/*
          if-no-files-found: warn
          retention-days: 14
